### ISSUE TITLE
Error Directly After Cloning and Running

### ISSUE THREAD

**Issue by jrneal1** [DHTMLX/react-gantt-demo#19]
I just cloned the repository, and ran "npm install" followed by "npm start".  The webpage rendered the following error:

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:375:7)
    at noopServiceWorkerMiddleware (C:\_GIT\react-gantt-demo\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (C:\_GIT\react-gantt-demo\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\_GIT\react-gantt-demo\node_modules\express\lib\router\index.js:317:13)
    at C:\_GIT\react-gantt-demo\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\_GIT\react-gantt-demo\node_modules\express\lib\router\index.js:335:12)
    at next (C:\_GIT\react-gantt-demo\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (C:\_GIT\react-gantt-demo\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (C:\_GIT\react-gantt-demo\node_modules\express\lib\router\layer.js:95:5)

**Comment by mcocchini** [comment]
Same problem here. Any solution?

**Comment by mcocchini** [comment]
Running `npm audit` gives this output:

>  High            Prototype Pollution
> 
>   Package         object-path
> 
>   Dependency of   react-scripts
> 
>   Path            react-scripts > resolve-url-loader > adjust-sourcemap-loader
>                   > object-path
> 
>   More info       https://npmjs.com/advisories/1573

So downgrading react-scripts @ 3.2.0 (instead of 3.3.1) solved the problem.
Hope it helps.

**Comment by jrneal1** [comment]
That worked!  Thanks @mcocchini.

And just to add some color around downgrading - i cloned the repo, and then before running 'npm install', I opened the package.json file and changed the "react-scripts" version from 3.3.1 to 3.2.0.  Then, I ran 'npm install' followed by 'npm start'.
